### ISSUE TITLE
SBT 3: IndexError: list index out of range

### ISSUE THREAD

**Issue by goliatone** [condemil/Gist#106]
This is the output of `Gist: Open Gist`

``` bash
Traceback (most recent call last):
  File "gist in /Users/goliatone/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 103, in _fn
  File "gist in /Users/goliatone/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 629, in run
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime.py", line 310, in show_quick_panel
    flat_items.append(items[i][j])
IndexError: list index out of range
error: Gist: unknown error (please, report a bug!)
```

**Comment by condemil** [comment]
I checked `show_authors` feature and it properly showing the authors in the open list. In case you still have this you can reopen the issue.
