### ISSUE TITLE
MissingCredentialsException

### ISSUE THREAD

**Issue by nifl** [condemil/Gist#143]
I added my token to Gist.sublime-settings (user) and am getting a MissingCredentialsException. I'm using ST3, build 3059.

```
Traceback (most recent call last):
  File "gist in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 31, in _fn
  File "gist in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 193, in on_gist_filename
  File "gist in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 54, in create_gist
  File "request in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 135, in api_request
  File "request in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 47, in api_request_native
  File "request in /Users/nifl/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 37, in token_auth_string
Gist.request.MissingCredentialsException
error: Gist: unknown error (please, report a bug!)
```

**Comment by condemil** [comment]
It looks like the issue is solved
