### ISSUE TITLE
gist plugin not loaded

### ISSUE THREAD

**Issue by kevinawoo** [condemil/Gist#183]
OS: OS X
OS Version: 10.12.5
Sublime Text Version: Dev 3139

Steps to reproduce the issue:

- install gist

Additional information (error message / screenshot):
```
reloading plugin Gist.gist
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "gist in /Users/kevinwoo/Library/Application Support/Sublime Text 3/Installed Packages/Gist.sublime-package", line 21, in <module>
ImportError: No module named 'gist_helpers'
```

**Comment by condemil** [comment]
Thanks for reporting this, the issue was related to import order (it is tricky in sublime and package control) and is already resolved.
